homeassistant:
  customize:
    sensor.unifi_office_ap:
      entity_picture: /local/img/unifi_ap_lite.png
command_line:
  - sensor:
      command: 'python3 /config/custom_components/unifi_status/unifi_office_ap.py'
      command_timeout: 60
      name: Unifi Office AP
      unique_id: unifi_office_ap
      value_template: '{{ value_json.Clients }}'
      unit_of_measurement: Clients
      scan_interval: 300
      json_attributes:
        - Guests
        - Clients_wifi0
        - Clients_wifi1
        - Score
        - CPU
        - RAM
        - Uptime
        - Score_wifi0
        - Score_wifi1
        - Activity
        - Update

template:
  - sensor:
      - unique_id: unifi_office_ap_guests
        state: >
          {{ states.sensor.unifi_office_ap.attributes.Guests }}
        attributes:
          friendly_name: Unifi Office AP Guests
      - unique_id: unifi_office_ap_activity
        state: >
          {{ states.sensor.unifi_office_ap.attributes.Activity }}
        attributes:
          friendly_name: Unifi Office AP Activity
          unit_of_measurement: 'Mbps'
      - unique_id: unifi_office_ap_ram
        state: >
          {{ states.sensor.unifi_office_ap.attributes.RAM }}
        attributes:
          friendly_name: Unifi Office AP RAM
          unit_of_measurement: '%'
      - unique_id: unifi_office_ap_cpu
        state: >
          {{ states.sensor.unifi_office_ap.attributes.CPU }}
        attributes:
          friendly_name: Unifi Office AP CPU
          unit_of_measurement: '%'
      - unique_id: unifi_office_ap_score
        state: >
          {{ states.sensor.unifi_office_ap.attributes.Score }}
        attributes:
          friendly_name: Unifi Office AP SCORE
      - unique_id: unifi_office_ap2_score
        state: >
          {% if is_state_attr('sensor.unifi_office_ap', 'Score_wifi0' , -1) %}
            N/A
          {% else %}
            {{ states.sensor.unifi_office_ap.attributes.Score_wifi0 }}.
          {% endif %}
        attributes:
          friendly_name: Unifi Office AP 2.4gHz SCORE
      - unique_id: unifi_office_ap5_score
        state: >
          {% if is_state_attr('sensor.unifi_office_ap', 'Score_wifi1' , -1) %}
            N/A
          {% else %}
            {{ states.sensor.unifi_office_ap.attributes.Score_wifi1 }}.
          {% endif %}
        attributes:
          friendly_name: Unifi Office AP 5gHz SCORE
      - unique_id: unifi_office_ap_2ghz_wifi_devices
        state: >
          {{ states.sensor.unifi_office_ap.attributes.Clients_wifi0 }}
        attributes:
          friendly_name: Unifi Office AP 2.4gHz Clients

      - unique_id: unifi_office_ap_5ghz_wifi_devices
        state: >
          {{ states.sensor.unifi_office_ap.attributes.Clients_wifi1 }}
        attributes:
          friendly_name: Unifi Office AP 5gHz Clients

      - unique_id: unifi_office_ap_update
        state: >
          {% if is_state_attr('sensor.unifi_office_ap', 'Update' , false) %}
            No
          {% else %}
            Available
          {% endif %}
        attributes:
          friendly_name: Unifi Office AP Updates
